name: enigma
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision=0.19.1 
  - pytorch-cuda=12.4
  - ipykernel=6.29.5 
  - huggingface_hub
  - pip
  - diffusers
  - ftfy
  - regex
  - tqdm
  - pytest
  - pyyaml
  - pandas=2.2.3
  - numpy>=2.1.0
  - jupyterlab
  - pip:
      - einops==0.8.0
      - open_clip_torch==2.26.1
      - opencv-python>=4.11.0.0
      - transformers>=4.51
      - click
      - pyarrow
      - attrs
      - scikit-learn
      - accelerate
      - ftfy
      - regex
      - kornia
      - omegaconf==2.3.0
      - git+https://github.com/openai/CLIP.git
